# Generated by Django 4.2.5 on 2023-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='feeling',
            field=models.CharField(choices=[('Love', 'Love'), ('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Funny', 'Funny')], default='sad', max_length=50),
        ),
    ]
