# Generated by Django 4.2.5 on 2023-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_alter_author_bio_alter_quote_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
