# Generated by Django 4.2.5 on 2023-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='feeling',
            field=models.CharField(choices=[('Love', 'Love'), ('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Funny', 'Funny'), ('Reflexive', 'Reflexive')], default='sad', max_length=50),
        ),
    ]
